# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/course_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
	def setupUi(self, Dialog):
		Dialog.setObjectName("Dialog")
		Dialog.resize(1200, 640)
		self.gridLayout = QtWidgets.QGridLayout(Dialog)
		self.gridLayout.setObjectName("gridLayout")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout()
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.indi_dept_label = QtWidgets.QLabel(Dialog)
		self.indi_dept_label.setObjectName("indi_dept_label")
		self.verticalLayout_2.addWidget(self.indi_dept_label)
		self.indi_num_label = QtWidgets.QLabel(Dialog)
		self.indi_num_label.setObjectName("indi_num_label")
		self.verticalLayout_2.addWidget(self.indi_num_label)
		self.indi_credits_label = QtWidgets.QLabel(Dialog)
		self.indi_credits_label.setObjectName("indi_credits_label")
		self.verticalLayout_2.addWidget(self.indi_credits_label)
		self.indi_title_label = QtWidgets.QLabel(Dialog)
		self.indi_title_label.setObjectName("indi_title_label")
		self.verticalLayout_2.addWidget(self.indi_title_label)
		self.indi_lab_hours_label = QtWidgets.QLabel(Dialog)
		self.indi_lab_hours_label.setObjectName("indi_lab_hours_label")
		self.verticalLayout_2.addWidget(self.indi_lab_hours_label)
		self.indi_lecture_hours_label = QtWidgets.QLabel(Dialog)
		self.indi_lecture_hours_label.setObjectName("indi_lecture_hours_label")
		self.verticalLayout_2.addWidget(self.indi_lecture_hours_label)
		self.indi_honors_label = QtWidgets.QLabel(Dialog)
		self.indi_honors_label.setObjectName("indi_honors_label")
		self.verticalLayout_2.addWidget(self.indi_honors_label)
		self.indi_description_label = QtWidgets.QLabel(Dialog)
		self.indi_description_label.setObjectName("indi_description_label")
		self.verticalLayout_2.addWidget(self.indi_description_label)
		self.indi_description_display = QtWidgets.QTextBrowser(Dialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.indi_description_display.sizePolicy().hasHeightForWidth())
		self.indi_description_display.setSizePolicy(sizePolicy)
		self.indi_description_display.setMinimumSize(QtCore.QSize(0, 0))
		self.indi_description_display.setMaximumSize(QtCore.QSize(200, 16777215))
		self.indi_description_display.setTextInteractionFlags(
			QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
		self.indi_description_display.setObjectName("indi_description_display")
		self.verticalLayout_2.addWidget(self.indi_description_display)
		self.indi_note_label = QtWidgets.QLabel(Dialog)
		self.indi_note_label.setObjectName("indi_note_label")
		self.verticalLayout_2.addWidget(self.indi_note_label)
		self.indi_offered_label = QtWidgets.QLabel(Dialog)
		self.indi_offered_label.setObjectName("indi_offered_label")
		self.verticalLayout_2.addWidget(self.indi_offered_label)
		self.indi_preqs_label = QtWidgets.QLabel(Dialog)
		self.indi_preqs_label.setObjectName("indi_preqs_label")
		self.verticalLayout_2.addWidget(self.indi_preqs_label)
		self.indi_recommended_label = QtWidgets.QLabel(Dialog)
		self.indi_recommended_label.setObjectName("indi_recommended_label")
		self.verticalLayout_2.addWidget(self.indi_recommended_label)
		self.indi_when_taught_label = QtWidgets.QLabel(Dialog)
		self.indi_when_taught_label.setObjectName("indi_when_taught_label")
		self.verticalLayout_2.addWidget(self.indi_when_taught_label)
		spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_2.addItem(spacerItem)
		self.horizontalLayout.addLayout(self.verticalLayout_2)
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.indi_sections_label = QtWidgets.QLabel(Dialog)
		self.indi_sections_label.setObjectName("indi_sections_label")
		self.verticalLayout.addWidget(self.indi_sections_label)
		self.indi_sections_table = QtWidgets.QTableWidget(Dialog)
		self.indi_sections_table.setObjectName("indi_sections_table")
		self.indi_sections_table.setColumnCount(12)
		self.indi_sections_table.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(7, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(8, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(9, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(10, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_sections_table.setHorizontalHeaderItem(11, item)
		self.verticalLayout.addWidget(self.indi_sections_table)
		self.indi_instructors_label = QtWidgets.QLabel(Dialog)
		self.indi_instructors_label.setObjectName("indi_instructors_label")
		self.verticalLayout.addWidget(self.indi_instructors_label)
		self.indi_instructors_table = QtWidgets.QTableWidget(Dialog)
		self.indi_instructors_table.setObjectName("indi_instructors_table")
		self.indi_instructors_table.setColumnCount(6)
		self.indi_instructors_table.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.indi_instructors_table.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_instructors_table.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_instructors_table.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_instructors_table.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_instructors_table.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.indi_instructors_table.setHorizontalHeaderItem(5, item)
		self.verticalLayout.addWidget(self.indi_instructors_table)
		self.horizontalLayout.addLayout(self.verticalLayout)
		self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

		self.retranslateUi(Dialog)
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
		self.indi_dept_label.setText(_translate("Dialog", "Dept\n"
		                                                  "---"))
		self.indi_num_label.setText(_translate("Dialog", "Num\n"
		                                                 "---"))
		self.indi_credits_label.setText(_translate("Dialog", "Credits\n"
		                                                     "---"))
		self.indi_title_label.setText(_translate("Dialog", "Title\n"
		                                                   "---"))
		self.indi_lab_hours_label.setText(_translate("Dialog", "Lab Hours\n"
		                                                       "---"))
		self.indi_lecture_hours_label.setText(_translate("Dialog", "Lecture Hours\n"
		                                                           "---"))
		self.indi_honors_label.setText(_translate("Dialog", "Honors\n"
		                                                    "---"))
		self.indi_description_label.setText(_translate("Dialog", "Description"))
		self.indi_description_display.setHtml(_translate("Dialog",
		                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
		                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
		                                                 "p, li { white-space: pre-wrap; }\n"
		                                                 "</style></head><body style=\" font-family:\'Cantarell\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
		                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is a big and long description of a class that\'s super long and verbose. This is a big and long description of a class that\'s super long and verbose. This is a big and long description of a class that\'s super long and verbose.</p></body></html>"))
		self.indi_note_label.setText(_translate("Dialog", "Note\n"
		                                                  "---"))
		self.indi_offered_label.setText(_translate("Dialog", "Offered\n"
		                                                     "---"))
		self.indi_preqs_label.setText(_translate("Dialog", "Prerequisites\n"
		                                                   "---"))
		self.indi_recommended_label.setText(_translate("Dialog", "Recommended\n"
		                                                         "---"))
		self.indi_when_taught_label.setText(_translate("Dialog", "When Taught\n"
		                                                         "---"))
		self.indi_sections_label.setText(_translate("Dialog", "Sections"))
		item = self.indi_sections_table.horizontalHeaderItem(0)
		item.setText(_translate("Dialog", "Section Num"))
		item = self.indi_sections_table.horizontalHeaderItem(1)
		item.setText(_translate("Dialog", "Type"))
		item = self.indi_sections_table.horizontalHeaderItem(2)
		item.setText(_translate("Dialog", "Instructor"))
		item = self.indi_sections_table.horizontalHeaderItem(3)
		item.setText(_translate("Dialog", "Start"))
		item = self.indi_sections_table.horizontalHeaderItem(4)
		item.setText(_translate("Dialog", "End"))
		item = self.indi_sections_table.horizontalHeaderItem(5)
		item.setText(_translate("Dialog", "Days"))
		item = self.indi_sections_table.horizontalHeaderItem(6)
		item.setText(_translate("Dialog", "Building"))
		item = self.indi_sections_table.horizontalHeaderItem(7)
		item.setText(_translate("Dialog", "Room"))
		item = self.indi_sections_table.horizontalHeaderItem(8)
		item.setText(_translate("Dialog", "Term"))
		item = self.indi_sections_table.horizontalHeaderItem(9)
		item.setText(_translate("Dialog", "Class Size"))
		item = self.indi_sections_table.horizontalHeaderItem(10)
		item.setText(_translate("Dialog", "Seats Available"))
		item = self.indi_sections_table.horizontalHeaderItem(11)
		item.setText(_translate("Dialog", "Waitlist Size"))
		self.indi_instructors_label.setText(_translate("Dialog", "Instructors"))
		item = self.indi_instructors_table.horizontalHeaderItem(0)
		item.setText(_translate("Dialog", "Sections"))
		item = self.indi_instructors_table.horizontalHeaderItem(1)
		item.setText(_translate("Dialog", "First Name"))
		item = self.indi_instructors_table.horizontalHeaderItem(2)
		item.setText(_translate("Dialog", "Last Name"))
		item = self.indi_instructors_table.horizontalHeaderItem(3)
		item.setText(_translate("Dialog", "# RMP Ratings"))
		item = self.indi_instructors_table.horizontalHeaderItem(4)
		item.setText(_translate("Dialog", "RMP Rating"))
		item = self.indi_instructors_table.horizontalHeaderItem(5)
		item.setText(_translate("Dialog", "RMP Difficulty"))
